<a href="https://colab.research.google.com/github/1aaronscott/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module2-loadingdata/LS_DS_112_Loading_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - Loading, Cleaning and Visualizing Data

Objectives for today:
- Load data from multiple sources into a Python notebook 
 - !curl method
 - CSV upload method
- Create basic plots appropriate for different data types
 - Scatter Plot
 - Histogram
 - Density Plot
 - Pairplot
- "Clean" a dataset using common Python libraries
 - Removing NaN values "Interpolation"

# Part 1 - Loading Data

Data comes in many shapes and sizes - we'll start by loading tabular data, usually in csv format.

Data set sources:

- https://archive.ics.uci.edu/ml/datasets.html
- https://github.com/awesomedata/awesome-public-datasets
- https://registry.opendata.aws/ (beyond scope for now, but good to be aware of)

Let's start with an example - [data about flags](https://archive.ics.uci.edu/ml/datasets/Flags).

## Lecture example - flag data

In [0]:
# Step 1 - find the actual file to download

# From navigating the page, clicking "Data Folder"
flag_data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/flags/flag.data'

# You can "shell out" in a notebook for more powerful tools
# https://jakevdp.github.io/PythonDataScienceHandbook/01.05-ipython-and-shell-commands.html

# Funny extension, but on inspection looks like a csv
!curl https://archive.ics.uci.edu/ml/machine-learning-databases/flags/flag.data

# Extensions are just a norm! You have to inspect to be sure what something is

In [0]:
# Step 2 - load the data

# How to deal with a csv? üêº
import pandas as pd
flag_data = pd.read_csv(flag_data_url)

In [0]:
# Step 3 - verify we've got *something*
flag_data.head()

,Afghanistan,5,1,648,16,10,2,0,3,5.1,...,0.5,0.6,1.6,0.7,0.8,1.7,0.9,0.10,black,green.1
0,Albania,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
1,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
2,American-Samoa,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
3,Andorra,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red
4,Angola,4,2,1247,7,10,5,0,2,3,...,0,0,1,0,0,1,0,0,red,black

In [0]:
# Step 4 - Looks a bit odd - verify that it is what we want
flag_data.count()

Afghanistan    193
5              193
1              193
648            193
16             193
10             193
2              193
0              193
3              193
5.1            193
1.1            193
1.2            193
0.1            193
1.3            193
1.4            193
1.5            193
0.2            193
green          193
0.3            193
0.4            193
0.5            193
0.6            193
1.6            193
0.7            193
0.8            193
1.7            193
0.9            193
0.10           193
black          193
green.1        193
dtype: int64

In [0]:
!curl https://archive.ics.uci.edu/ml/machine-learning-databases/flags/flag.data | wc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15240  100 15240    0     0  92363      0 --:--:-- --:--:-- --:--:-- 92363
    194     194   15240

In [0]:
# So we have 193 observations with funny names, file has 194 rows
# Looks like the file has no header row, but read_csv assumes it does
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts either
        ``pathlib.Path`` or ``py._path.local.LocalPath``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handler (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, default ``None``
        Alias for sep.
    header : int, list of int, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : array-like, optional
        List of column names to use. If file contains no header row, then you
        should explicitly pass ``header=None``. Duplicates in this list will cause
        a ``UserWarning`` to be issued.
    index_col : int, sequence or bool, optional
        Column to use as the row labels of the DataFrame. If a sequence is given, a
        MultiIndex is used. If you have a malformed file with delimiters at the end
        of each line, you might consider ``index_col=False`` to force pandas to
        not use the first column as the index (row names).
    usecols : list-like or callable, optional
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). For example, a valid list-like
        `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : bool, default False
        If the parsed data only contains one column then return a Series.
    prefix : str, optional
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
    mangle_dupe_cols : bool, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, optional
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
        'c': 'Int64'}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python'}, optional
        Parser engine to use. The C engine is faster while the python engine is
        currently more feature-complete.
    converters : dict, optional
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels.
    true_values : list, optional
        Values to consider as True.
    false_values : list, optional
        Values to consider as False.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : list-like, int or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c').
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : scalar, str, list-like, or dict, optional
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
        'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    skip_blank_lines : bool, default True
        If True, skip over blank lines rather than interpreting as NaN values.
    parse_dates : bool or list of int or names or list of lists or dict, default False
        The behavior is as follows:

        * boolean. If True -> try parsing the index.
        * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index cannot be represented as an array of datetimes,
        say because of an unparseable value or a mixture of timezones, the column
        or index will be returned unaltered as an object data type. For
        non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_csv``. To parse an index or column with a mixture of timezones,
        specify ``date_parser`` to be a partially-applied
        :func:`pandas.to_datetime` with ``utc=True``. See
        :ref:`io.csv.mixed_timezones` for more.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : bool, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    iterator : bool, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and
        `filepath_or_buffer` is path-like, then detect compression from the
        following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        decompression). If using 'zip', the ZIP file must contain only one data
        file to be read in. Set to None for no decompression.

        .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

    thousands : str, optional
        Thousands separator.
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    lineterminator : str (length 1), optional
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : bool, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        One-character string used to escape other characters.
    comment : str, optional
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, optional
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .
    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    tupleize_cols : bool, default False
        Leave a list of tuples on columns as is (default is to convert to
        a MultiIndex on the columns).

        .. deprecated:: 0.21.0
           This argument will be removed and will always convert to MultiIndex

    error_bad_lines : bool, default True
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will dropped from the DataFrame that is
        returned.
    warn_bad_lines : bool, default True
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.
    delim_whitespace : bool, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.

        .. versionadded:: 0.18.1 support for the Python parser.

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : str, optional
        Specifies which converter the C engine should use for floating-point
        values. The options are `None` for the ordinary converter,
        `high` for the high-precision converter, and `round_trip` for the
        round-trip converter.

    Returns
    -------
    DataFrame or TextParser
        A comma-separated values (csv) file is returned as two-dimensional
        data structure with labeled axes.

    See Also
    --------
    to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Examples
    --------
    >>> pd.read_csv('data.csv')  # doctest: +SKIP

In [0]:
?pd.read_csv

In [0]:
??pd.read_csv

In [0]:
# Alright, we can pass header=None to fix this
flag_data = pd.read_csv(flag_data_url, header=None)
flag_data.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,Afghanistan,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
1,Albania,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
2,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red

In [0]:
flag_data.count()

0     194
1     194
2     194
3     194
4     194
5     194
6     194
7     194
8     194
9     194
10    194
11    194
12    194
13    194
14    194
15    194
16    194
17    194
18    194
19    194
20    194
21    194
22    194
23    194
24    194
25    194
26    194
27    194
28    194
29    194
dtype: int64

In [0]:
flag_data.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

### Yes, but what does it *mean*?

This data is fairly nice - it was "donated" and is already "clean" (no missing values). But there are no variable names - so we have to look at the codebook (also from the site).

```
1. name: Name of the country concerned
2. landmass: 1=N.America, 2=S.America, 3=Europe, 4=Africa, 4=Asia, 6=Oceania
3. zone: Geographic quadrant, based on Greenwich and the Equator; 1=NE, 2=SE, 3=SW, 4=NW
4. area: in thousands of square km
5. population: in round millions
6. language: 1=English, 2=Spanish, 3=French, 4=German, 5=Slavic, 6=Other Indo-European, 7=Chinese, 8=Arabic, 9=Japanese/Turkish/Finnish/Magyar, 10=Others
7. religion: 0=Catholic, 1=Other Christian, 2=Muslim, 3=Buddhist, 4=Hindu, 5=Ethnic, 6=Marxist, 7=Others
8. bars: Number of vertical bars in the flag
9. stripes: Number of horizontal stripes in the flag
10. colours: Number of different colours in the flag
11. red: 0 if red absent, 1 if red present in the flag
12. green: same for green
13. blue: same for blue
14. gold: same for gold (also yellow)
15. white: same for white
16. black: same for black
17. orange: same for orange (also brown)
18. mainhue: predominant colour in the flag (tie-breaks decided by taking the topmost hue, if that fails then the most central hue, and if that fails the leftmost hue)
19. circles: Number of circles in the flag
20. crosses: Number of (upright) crosses
21. saltires: Number of diagonal crosses
22. quarters: Number of quartered sections
23. sunstars: Number of sun or star symbols
24. crescent: 1 if a crescent moon symbol present, else 0
25. triangle: 1 if any triangles present, 0 otherwise
26. icon: 1 if an inanimate image present (e.g., a boat), otherwise 0
27. animate: 1 if an animate image (e.g., an eagle, a tree, a human hand) present, 0 otherwise
28. text: 1 if any letters or writing on the flag (e.g., a motto or slogan), 0 otherwise
29. topleft: colour in the top-left corner (moving right to decide tie-breaks)
30. botright: Colour in the bottom-left corner (moving left to decide tie-breaks)
```

Exercise - read the help for `read_csv` and figure out how to load the data with the above variable names. One pitfall to note - with `header=None` pandas generated variable names starting from 0, but the above list starts from 1...

## Loading from a local CSV to Google Colab

# Part 2 - Basic Visualizations

## Basic Data Visualizations Using Matplotlib

In [0]:
import matplotlib.pyplot as plt

# Scatter Plot

In [0]:
# Histogram

In [0]:
# Seaborn Density Plot

In [0]:
# Seaborn Pairplot

## Create the same basic Visualizations using Pandas

In [0]:
# Pandas Histogram - Look familiar?

In [0]:
# Pandas Scatterplot

In [0]:
# Pandas Scatter Matrix - Usually doesn't look too great.

# Part 3 - Deal with Missing Values

## Diagnose Missing Values

Lets use the Adult Dataset from UCI. <https://github.com/ryanleeallred/datasets>

## Fill Missing Values

## Your assignment - pick a dataset and do something like the above

This is purposely open-ended - you can pick any data set you wish. It is highly advised you pick a dataset from UCI or a similar semi-clean source. You don't want the data that you're working with for this assignment to have any bigger issues than maybe not having headers or including missing values, etc.

After you have chosen your dataset, do the following:

- Import the dataset using the method that you are least comfortable with (!curl or CSV upload).
 - Make sure that your dataset has the number of rows and columns that you expect.
 - Make sure that your dataset has appropriate column names, rename them if necessary.
 - If your dataset uses markers like "?" to indicate missing values, replace them with NaNs during import.
- Identify and fill missing values in your dataset (if any)
 - Don't worry about using methods more advanced than the `.fillna()` function for today.
- Create one of each of the following plots using your dataset
 - Scatterplot
 - Histogram
 - Density Plot
 - Pairplot (note that pairplots will take a long time to load with large datasets or datasets with many columns)

If you get that done and want to try more challenging or exotic things, go for it! Use documentation as illustrated above, and follow the 20-minute rule (that is - ask for help if you're stuck!).

If you have loaded a few traditional datasets, see the following section for suggested stretch goals.

In [0]:
# TODO your work here!
# And note you should write comments, descriptions, and add new
# code and text blocks as needed
dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00397/LasVegasTripAdvisorReviews-Dataset.csv'

import pandas as pd
vegas_data = pd.read_csv(dataset_url, delimiter=';')
vegas_data.head(30)
#this data set used semicolons as the delimiter but had some values with commas which confused pandas

In [19]:
#check number of colums and rows (20x504 according to UCI)
vegas_data.shape

(504, 20)

In [21]:
#find any missing data. UCI doesn't provide a value
vegas_data.isna().sum()

User country         0
Nr. reviews          0
Nr. hotel reviews    0
Helpful votes        0
Score                0
Period of stay       0
Traveler type        0
Pool                 0
Gym                  0
Tennis court         0
Spa                  0
Casino               0
Free internet        0
Hotel name           0
Hotel stars          0
Nr. rooms            0
User continent       0
Member years         0
Review month         0
Review weekday       0
dtype: int64

In [0]:
#scatter plot
vegas_data.

In [0]:
#histogram

In [0]:
#density plot

In [0]:
#pair plot
import seaborn as sns

## Stretch Goals - Other types and sources of data

Not all data comes in a nice single file - for example, image classification involves handling lots of image files. You still will probably want labels for them, so you may have tabular data in addition to the image blobs - and the images may be reduced in resolution and even fit in a regular csv as a bunch of numbers.

If you're interested in natural language processing and analyzing text, that is another example where, while it can be put in a csv, you may end up loading much larger raw data and generating features that can then be thought of in a more standard tabular fashion.

Overall you will in the course of learning data science deal with loading data in a variety of ways. Another common way to get data is from a database - most modern applications are backed by one or more databases, which you can query to get data to analyze. We'll cover this more in our data engineering unit.

How does data get in the database? Most applications generate logs - text files with lots and lots of records of each use of the application. Databases are often populated based on these files, but in some situations you may directly analyze log files. The usual way to do this is with command line (Unix) tools - command lines are intimidating, so don't expect to learn them all at once, but depending on your interests it can be useful to practice.

One last major source of data is APIs: https://github.com/toddmotto/public-apis

API stands for Application Programming Interface, and while originally meant e.g. the way an application interfaced with the GUI or other aspects of an operating system, now it largely refers to online services that let you query and retrieve data. You can essentially think of most of them as "somebody else's database" - you have (usually limited) access.

*Stretch goal* - research one of the above extended forms of data/data loading. See if you can get a basic example working in a notebook. Image, text, or (public) APIs are probably more tractable - databases are interesting, but there aren't many publicly accessible and they require a great deal of setup.

In [22]:
#cell with raw data to scan for errors or incomplete data
!curl "https://archive.ics.uci.edu/ml/machine-learning-databases/00397/LasVegasTripAdvisorReviews-Dataset.csv"

User country;Nr. reviews;Nr. hotel reviews;Helpful votes;Score;Period of stay;Traveler type;Pool;Gym;Tennis court;Spa;Casino;Free internet;Hotel name;Hotel stars;Nr. rooms;User continent;Member years;Review month;Review weekday
USA;11;4;13;5;Dec-Feb;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;9;January;Thursday
USA;119;21;75;3;Dec-Feb;Business;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;3;January;Friday
USA;36;9;25;5;Mar-May;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;2;February;Saturday
UK;14;7;14;4;Mar-May;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Europe;6;February;Friday
Canada;5;5;2;4;Mar-May;Solo;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;7;March;Tuesday
Canada;31;8;27;3;Mar-May;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;2;March;Tuesday
UK;45;12;46;4;Mar-May;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Europe;4;April;Friday
USA;2;1;4;4;Mar-May;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;0;April;Tuesday
India;24;3;8;4;Mar-May;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Asia;3;May;Saturday
Canada;12;7;11;3;Mar-May;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;5;May;Tuesday
USA;102;24;58;2;Jun-Aug;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;9;June;Friday
Australia;20;9;24;3;Jun-Aug;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Oceania;4;June;Saturday
USA;7;6;9;2;Jun-Aug;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;1;July;Wednesday
USA;22;5;13;3;Jun-Aug;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;1;July;Thursday
UK;3;3;0;3;Jun-Aug;Friends;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Europe;1;August;Sunday
New Zeland;146;17;33;4;Jun-Aug;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Oceania;2;August;Saturday
Canada;8;8;9;1;Sep-Nov;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;4;September;Wednesday
USA;9;3;1;4;Sep-Nov;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;2;September;Saturday
Canada;41;9;19;3;Sep-Nov;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;2;October;Tuesday
USA;8;7;26;2;Sep-Nov;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;10;October;Monday
UK;10;5;2;4;Sep-Nov;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Europe;7;November;Saturday
New Zeland;4;3;3;1;Sep-Nov;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Oceania;3;November;Monday
UK;18;7;19;4;Dec-Feb;Families;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;Europe;0;December;Saturday
USA;4;4;3;2;Dec-Feb;Couples;NO;YES;NO;NO;YES;YES;Circus Circus Hotel & Casino Las Vegas;3;3773;North America;5;December;Sunday
Ireland;29;11;15;4;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;3;January;Monday
USA;114;42;52;4;Dec-Feb;Business;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;11;January;Saturday
Canada;30;12;17;5;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;8;February;Friday
UK;87;18;36;3;Dec-Feb;Business;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;3;February;Thursday
USA;26;10;28;5;Mar-May;Solo;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;1;March;Wednesday
Ireland;8;7;9;5;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;8;March;Wednesday
Canada;11;8;13;5;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;7;April;Friday
Australia;4;3;2;3;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Oceania;0;April;Friday
Canada;56;8;7;3;Mar-May;Solo;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;1;May;Tuesday
Egypt;13;12;8;3;Mar-May;Friends;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Africa;4;May;Wednesday
Australia;58;9;15;4;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Oceania;0;June;Saturday
Finland;20;7;4;3;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;6;June;Saturday
USA;70;27;24;4;Jun-Aug;Friends;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;6;July;Friday
Kenya;6;3;7;4;Jun-Aug;Friends;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Africa;1;July;Thursday
USA;290;263;299;4;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;10;August;Monday
USA;24;6;9;2;Jun-Aug;Families;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;2;August;Wednesday
Jordan;29;8;21;3;Sep-Nov;Business;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;2;September;Wednesday
Canada;20;5;59;3;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;8;September;Saturday
Netherlands;3;3;3;3;Sep-Nov;Families;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;4;October;Saturday
Ireland;47;6;27;4;Sep-Nov;Friends;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;5;October;Monday
USA;35;8;19;4;Sep-Nov;Families;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;North America;6;November;Sunday
UK;6;0;4;4;Sep-Nov;Friends;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;1;November;Sunday
UK;74;47;54;4;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Europe;7;December;Wednesday
Syria;34;8;30;3;Dec-Feb;Solo;YES;YES;NO;YES;YES;YES;Excalibur Hotel & Casino;3;3981;Asia;4;December;Tuesday
UK;576;43;340;3;Dec-Feb;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;3;January;Monday
USA;20;8;11;4;Dec-Feb;Solo;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;5;January;Saturday
USA;418;32;132;2;Dec-Feb;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;3;February;Tuesday
USA;73;13;22;4;Dec-Feb;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;2;February;Tuesday
Canada;30;10;32;3;Mar-May;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;2;March;Wednesday
USA;63;15;17;4;Mar-May;Business;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;2;March;Tuesday
Scotland;24;10;13;5;Mar-May;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;5;April;Wednesday
South Africa;54;18;16;2;Mar-May;Business;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Africa;5;April;Tuesday
Australia;20;7;11;4;Mar-May;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Oceania;2;May;Friday
UK;41;7;24;4;Mar-May;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;3;May;Monday
Ireland;7;5;7;4;Jun-Aug;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;9;June;Tuesday
Canada;13;9;15;4;Jun-Aug;Friends;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;1;June;Monday
UK;10;5;4;4;Jun-Aug;Families;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;1;July;Friday
New Zeland;9;6;19;3;Jun-Aug;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Oceania;7;July;Wednesday
Swiss;36;19;36;2;Jun-Aug;Solo;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;5;August;Thursday
UK;33;12;19;3;Jun-Aug;Families;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;5;August;Saturday
United Arab Emirates;156;126;142;3;Sep-Nov;Friends;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Asia;8;September;Friday
Ireland;19;17;16;4;Sep-Nov;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;5;September;Wednesday
USA;23;17;11;3;Sep-Nov;Families;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;1;October;Friday
USA;13;3;3;2;Sep-Nov;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;1;October;Sunday
Hungary;8;5;8;4;Sep-Nov;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;8;November;Friday
China;1;0;2;1;Sep-Nov;Business;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Asia;0;November;Wednesday
Greece;21;18;6;2;Dec-Feb;Business;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;Europe;0;December;Sunday
Mexico;56;14;36;5;Dec-Feb;Couples;YES;YES;NO;YES;YES;NO;Monte Carlo Resort&Casino;4;3003;North America;3;December;Monday
Croatia;29;11;14;3;Dec-Feb;Business;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Europe;6;January;Sunday
Australia;11;5;8;4;Dec-Feb;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Oceania;1;January;Thursday
Canada;19;12;167;4;Dec-Feb;Friends;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;9;February;Monday
USA;17;9;16;5;Dec-Feb;Solo;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;-1806;February;Monday
USA;43;8;20;4;Mar-May;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;1;March;Friday
Canada;12;8;3;4;Mar-May;Friends;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;2;March;Saturday
USA;15;14;7;4;Mar-May;Friends;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;9;April;Tuesday
Australia;16;13;16;3;Mar-May;Families;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Oceania;6;April;Wednesday
India;12;4;25;3;Mar-May;Families;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Asia;1;May;Friday
Germany;10;0;5;4;Mar-May;Friends;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Europe;3;May;Sunday
USA;27;17;16;3;Jun-Aug;Families;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;6;June;Thursday
Canada;6;5;5;4;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;2;June;Tuesday
Australia;21;20;14;5;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Oceania;3;July;Wednesday
Malaysia;43;14;27;4;Jun-Aug;Solo;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Asia;5;July;Thursday
Mexico;97;31;37;4;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;South America;8;August;Saturday
UK;7;3;4;4;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Europe;5;August;Friday
UK;11;9;6;3;Sep-Nov;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Europe;0;September;Friday
USA;78;11;30;4;Sep-Nov;Business;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;2;September;Tuesday
Australia;12;7;4;5;Sep-Nov;Families;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Oceania;5;October;Monday
USA;27;11;5;3;Sep-Nov;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;2;October;Monday
Thailand;4;3;1;5;Sep-Nov;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Asia;7;November;Friday
Australia;27;9;8;4;Sep-Nov;Families;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;Oceania;2;November;Friday
Canada;12;3;7;4;Dec-Feb;Friends;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;4;December;Saturday
Canada;21;16;48;5;Dec-Feb;Couples;YES;YES;YES;YES;YES;YES;Treasure Island- TI Hotel & Casino;4;2884;North America;12;December;Thursday
UK;34;17;30;4;Dec-Feb;Families;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;8;January;Sunday
USA;12;6;1;5;Dec-Feb;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;North America;2;January;Sunday
Phillippines;79;39;51;3;Dec-Feb;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Asia;5;February;Wednesday
Israel;18;10;16;3;Dec-Feb;Business;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Asia;2;February;Thursday
Canada;13;3;8;4;Mar-May;Business;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;North America;3;March;Wednesday
UK;14;4;9;4;Mar-May;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;1;March;Friday
Ireland;19;9;28;5;Mar-May;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;3;April;Friday
India ;88;15;103;4;Mar-May;Business;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Asia;3;April;Monday
New Zeland;8;4;0;4;Mar-May;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Oceania;1;May;Tuesday
Belgium;39;15;31;3;Mar-May;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;1;May;Sunday
UK;130;41;61;4;Jun-Aug;Business;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;3;June;Tuesday
Australia;79;78;105;4;Jun-Aug;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Oceania;7;June;Wednesday
UK;13;10;16;4;Jun-Aug;Solo;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;10;July;Wednesday
UK;18;6;17;4;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;1;July;Monday
New Zeland;8;7;3;5;Jun-Aug;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Oceania;1;August;Saturday
Australia;15;4;6;5;Jun-Aug;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Oceania;0;August;Friday
Canada;27;0;9;1;Sep-Nov;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;North America;0;September;Tuesday
Australia;5;3;2;5;Sep-Nov;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Oceania;5;September;Wednesday
UK;22;6;6;5;Sep-Nov;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;1;October;Tuesday
USA;5;3;11;2;Sep-Nov;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;North America;1;October;Thursday
India;31;8;11;4;Sep-Nov;Solo;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Asia;1;November;Sunday
Netherlands;33;8;8;5;Sep-Nov;Friends;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;7;November;Saturday
UK;10;6;11;5;Dec-Feb;Couples;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;4;December;Saturday
UK;12;3;3;5;Dec-Feb;Families;YES;YES;YES;YES;YES;YES;Tropicana Las Vegas - A Double Tree by Hilton Hotel;4;1467;Europe;4;December;Thursday
USA;50;14;24;5;Dec-Feb;Friends;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;7;January;Wednesday
USA;161;33;85;4;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;3;January;Friday
Puerto Rico;153;38;81;5;Dec-Feb;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;10;February;Tuesday
Canada;14;3;12;5;Dec-Feb;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;2;February;Thursday
USA;31;12;10;5;Mar-May;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;4;March;Friday
USA;15;10;29;3;Mar-May;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;9;March;Friday
Canada;5;5;4;5;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;3;April;Thursday
USA;46;4;21;4;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;2;April;Saturday
UK;15;6;39;1;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Europe;4;May;Sunday
UK;63;27;35;4;Mar-May;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Europe;5;May;Wednesday
USA;17;15;13;4;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;2;June;Sunday
USA;25;22;36;1;Jun-Aug;Solo;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;9;June;Tuesday
USA;14;8;4;5;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;1;July;Monday
UK;59;56;37;3;Jun-Aug;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Europe;6;July;Tuesday
UK;11;10;17;5;Jun-Aug;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Europe;3;August;Friday
Canada;54;18;31;4;Jun-Aug;Friends;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;5;August;Wednesday
USA;4;3;4;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;3;September;Monday
USA;10;7;7;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;3;September;Tuesday
USA;14;6;7;5;Sep-Nov;Business;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;11;October;Sunday
USA;39;12;16;5;Sep-Nov;Friends;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;2;October;Thursday
Australia;35;24;43;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Oceania;4;November;Sunday
Australia;6;6;9;3;Sep-Nov;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;Oceania;0;November;Sunday
USA;23;7;2;4;Dec-Feb;Families;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;3;December;Friday
USA;48;21;67;4;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;Caesars Palace;5;3348;North America;13;December;Sunday
Australia;16;9;14;4;Dec-Feb;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Oceania;3;January;Thursday
Australia;12;6;3;5;Dec-Feb;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Oceania;1;January;Thursday
Switzerland;36;9;15;4;Dec-Feb;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;2;February;Saturday
UK;127;40;80;5;Dec-Feb;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;8;February;Wednesday
USA;12;5;1;5;Mar-May;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;1;March;Monday
USA;17;17;74;5;Mar-May;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;10;March;Saturday
Ireland;23;7;21;4;Mar-May;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;7;April;Thursday
USA;102;17;45;5;Mar-May;Business;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;2;April;Monday
Germany;113;15;55;5;Mar-May;Families;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;8;May;Thursday
USA;30;8;10;2;Mar-May;Business;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;1;May;Wednesday
Germany;24;24;24;2;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;7;June;Wednesday
Ireland;15;5;18;5;Jun-Aug;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;3;June;Wednesday
USA;6;4;14;1;Jun-Aug;Business;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;1;July;Wednesday
Australia;3;3;0;4;Jun-Aug;Friends;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Oceania;7;July;Tuesday
Canada;41;10;56;5;Jun-Aug;Families;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;4;August;Saturday
USA;19;8;56;4;Jun-Aug;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;10;August;Sunday
UK;18;9;10;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;1;September;Wednesday
Norway;6;6;7;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;Europe;7;September;Tuesday
USA;103;5;98;5;Sep-Nov;Couples;YES;YES;NO;YES;YES;YES;The Cosmopolitan Las Vegas;5;2959;North America;7;October;Monday